### ISSUE TITLE
Can popper send mail body as message to Slack?

### ISSUE THREAD

**Issue by tnmt** [pyama86/popper#8]
I guess that popper cannot send mail body as message to Slack because to avoid miss transmission that have sensitive information.

Do you have any plan to implement about that as main function ?

**Comment by pyama86** [comment]
> I guess that popper cannot send mail body as message to Slack because to avoid miss transmission that have sensitive information.

you are right.

> Do you have any plan to implement about that as main function ?

i don't implement to put mail body. in that case use slack email integration.

thank you!

**Comment by tnmt** [comment]
I got it. I'll try to use Email Integration.

Thanks for your comment.
